name: Build macOS only

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short
  HUSKY: 0

jobs:
  build-macos:
    name: Build macOS
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: '1.98.1'
          targets: ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/dev' }}
          prefix-key: 'v1-rust'
          key: 'rust-shared-stable-${{ matrix.os }}-${{ matrix.target }}'
          workspaces: |
            . -> target
          cache-all-crates: true
          cache-workspace-crates: true

      - uses: pnpm/action-setup@v6.1.0
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: '24.20.0'
          cache: 'pnpm'

      - name: Pnpm Cache
        uses: actions/cache@v6
        with:
          path: ~/.pnpm-store
          key: 'pnpm-shared-stable-${{ matrix.os }}-${{ matrix.target }}'
          restore-keys: |
            pnpm-shared-stable-${{ matrix.os }}-${{ matrix.target }}

      - name: Pnpm install and prebuild
        run: |
          pnpm i
          pnpm run prebuild ${{ matrix.target }}

      - name: Tauri build for macOS
        uses: tauri-apps/tauri-action@v1
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: 'macos-build'
          releaseName: 'Clash Verge Rev macOS'
          releaseBody: 'macOS-only build'
          releaseDraft: false
          prerelease: true
          tauriScript: pnpm
          args: --target ${{ matrix.target }} --config src-tauri/tauri.macos.ci.conf.json
